# EXAMPLE OF COMMITTING AND ROLLING BACK A TRANSACTION
DELIMITER //
CREATE PROCEDURE TRANSACTION_ROSE()
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
		ROLLBACK;
        RESIGNAL;
	END;
    START TRANSACTION;
    UPDATE BANKACCOUNTS
    SET BALANCE = BALANCE - 200
    WHERE ACCOUNTNAME = 'Rose';
    
    UPDATE BANKACCOUNTS
    SET BALANCE = BALANCE + 200
    WHERE ACCOUNTNAME = 'Shoe Shop';
    
    UPDATE SHOESHOP
    SET STOCK = STOCK - 1
    WHERE PRODUCT = 'Boots';
    
    UPDATE BANKACCOUNTS
    SET BALANCE = BALANCE - 300
    WHERE ACCOUNTNAME = 'Rose';
    
    COMMIT;
END //

DELIMITER ;

CALL TRANSACTION_ROSE;
SELECT * FROM BankAccounts;

    