DELIMITER //
CREATE PROCEDURE RETRIEVE_ALL()
BEGIN
	SELECT * FROM PETSALE;
END //
DELIMITER;

CALL RETRIEVE_ALL;

# TASK 2:
DELIMITER @
CREATE PROCEDURE UPDATE_SALEPRICE (IN ANIMAL_ID INTEGER, IN ANIMAL_HEALTH VARCHAR(5))
BEGIN
	IF ANIMAL_HEALTH = 'BAD' THEN
		UPDATE PETSALE
        SET SALEPRICE = SALEPRICE - (SALEPRICE * 0.25)
        WHERE ID = ANIMAL_ID;
	ELSEIF ANIMAL_HEALTH = 'WORSE' THEN
		UPDATE PETSALE
        SET SALEPRICE = SALEPRICE - (SALEPRICE * 0.5)
        WHERE ID = ANIMAL_ID;
	ELSE
		UPDATE PETSALE
        SET SALEPRICE = SALEPRICE
        WHERE ID = ANIMAL_ID;
	END IF;
END @

DELIMITER;    

   CALL UPDATE_SALEPRICE(1, 'BAD');
   CALL RETRIEVE_ALL;
   
   CALL UPDATE_SALEPRICE(3,'WORSE');
   CALL RETRIEVE_ALL;



