CREATE VIEW EMPSALARY AS
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, SALARY
FROM EMPLOYEES;

SELECT * FROM EMPSALARY;

# TASK 2: UPDATE A VIEW
CREATE OR REPLACE VIEW EMPSALARY AS 
SELECT EMP_ID, F_NAME, L_NAME, B_DATE, SEX, JOB_TITLE, MIN_SALARY, MAX_SALARY
FROM EMPLOYEES E, JOBS J
WHERE E.JOB_ID = J.JOB_IDENT;

SELECT * FROM EMPSALARY;

# TASK 3: DROP A VIEW
DROP VIEW EMPSALARY;

# PRACTICE PROBLEMS
# 1. Create a view “EMP_DEPT” with EMP_ID, FNAME, LNAME and DEP_ID from EMPLOYEES table
CREATE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_ID
FROM EMPLOYEES;

# 2. Modify “EMP_DEPT” such that it displays Department names instead of Department IDs. 
# For this, we need to combine information from EMPLOYEES and DEPARTMENTS as follows. 
# EMP_ID, FNAME, LNAME from EMPLOYEES table and
# DEP_NAME from DEPARTMENTS table, combined over the columns DEP_ID and DEPT_ID_DEP.

CREATE OR REPLACE VIEW EMP_DEPT AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE D.DEPT_ID_DEP = E.DEP_ID;

SELECT * FROM EMP_DEPT



